apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: mysql
namePrefix: mysql-

resources:
- mysql-statefulset.yaml
- mysql-service.yaml
- mysql-secret.yaml
- mysql-pv.yaml
- mysql-pvc.yaml